### ISSUE TITLE
Issue creating new proxy configuration

### ISSUE THREAD

**Issue by jslee98** [apify/apify-sdk-python#122]
Getting a key error on “password” when trying to create a proxy configuration - no code changes or account changes prompted this error.

It is very distruptive to my business, would appreciate insight on how to fix

```
2023-10-11T15:01:03.368Z ACTOR: Pulling Docker image of build 3Smg9ebZRQOrnkmCZ from repository.
2023-10-11T15:01:03.581Z ACTOR: Creating Docker container.
2023-10-11T15:01:03.640Z ACTOR: Starting Docker container.
2023-10-11T15:01:06.513Z INFO  Initializing actor...
2023-10-11T15:01:06.515Z INFO  System info ({"apify_sdk_version": "1.1.4", "apify_client_version": "1.4.1", "python_version": "3.11.5", "os": "linux"})
2023-10-11T15:01:07.173Z ERROR Actor failed with an exception
2023-10-11T15:01:07.176Z       Traceback (most recent call last):
2023-10-11T15:01:07.178Z         File "/usr/src/app/src/main.py", line 31, in main
2023-10-11T15:01:07.180Z           proxy = await Actor.create_proxy_configuration(
2023-10-11T15:01:07.182Z                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-10-11T15:01:07.184Z         File "/opt/venv/lib/python3.11/site-packages/apify/actor.py", line 1285, in create_proxy_configuration
2023-10-11T15:01:07.186Z           return await cls._get_default_instance().create_proxy_configuration(
2023-10-11T15:01:07.188Z                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-10-11T15:01:07.190Z         File "/opt/venv/lib/python3.11/site-packages/apify/actor.py", line 1325, in _create_proxy_configuration_internal
2023-10-11T15:01:07.196Z           await proxy_configuration.initialize()
2023-10-11T15:01:07.199Z         File "/opt/venv/lib/python3.11/site-packages/apify/proxy_configuration.py", line 197, in initialize
2023-10-11T15:01:07.201Z           await self._maybe_fetch_password()
2023-10-11T15:01:07.203Z         File "/opt/venv/lib/python3.11/site-packages/apify/proxy_configuration.py", line 298, in _maybe_fetch_password
2023-10-11T15:01:07.205Z           password = user_info['proxy']['password']
2023-10-11T15:01:07.207Z                      ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
2023-10-11T15:01:07.209Z       KeyError: 'password'
2023-10-11T15:01:07.211Z INFO  Exiting actor ({"exit_code": 91})
```

**Comment by jslee98** [comment]
looks like this was resolved without any client changes
